### ISSUE TITLE
Internet radio playback does not resume when unlocking the PC

### ISSUE THREAD

**Issue by XelaNimed** [KorneySan/AIMP-plugins#2]
`AIMP v.5.11.2421 x32`
`Win 10 Pro 21H2 x64 (Build 19044.2604)`
`AutoPause v.0.8.2`

#### Plugin settings
- PC lock
     - pause
     - Continue playback when unlocked (selected and active)
- Simple PC
     - Nothing
     - Continue playback when user activity resumes (selected but not active)
- Launched screensaver
     - Nothing
     - Continue playback when screensaver closes (selected but not active)

#### Error
When playing a stream (Internet radio) and locking the screen (Win + L), playback is paused, but when unlocked, it does not resume.

**Comment by KorneySan** [comment]
It is due to STOPPING of Internet radio instead of pausing (internally in player).
Will fix ASAP.

**Comment by KorneySan** [comment]
Fixed in AIMP 5.11.2427 by AIMP author.
